language: rust
sudo: false
cache: cargo
rust:
- stable
- beta
- nightly
os:
- linux
- osx
script:
- cargo test --verbose
- cargo test --verbose --features=colored
- cargo test --verbose --features=syslog-3
- cargo test --verbose --all-features
- cargo run --example cmd-program
- cargo run --example cmd-program -- --verbose
- cargo run --example colored --features colored
