language: rust
sudo: false
cache: cargo
rust:
- stable
- beta
- nightly
before_script:
- export PATH="$PATH:$HOME/.cargo/bin"
script:
- cargo build --verbose
- cargo test --verbose -- --skip test2 --skip test3
- cargo test --verbose test2
- cargo test --verbose test3
- cargo test --verbose --all-features -- --skip test2 --skip test3
- cargo run --example cmd-program
- cargo run --example cmd-program -- --verbose
- cargo run --example colored --features colored
