language: rust
sudo: false
cache: cargo
rust:
- stable
- beta
- nightly
os:
- linux
- osx
matrix:
  include:
  - os: linux
    rust: 1.16.0
    script: cargo build --verbose
script:
- cargo test --verbose
- cargo test --verbose --features=colored
- cargo test --verbose --features=syslog-3
- cargo test --verbose --all-features
- cargo run --example cmd-program
- cargo run --example cmd-program -- --verbose
- cargo run --example colored --features colored
