language: rust

env:
  global:
    - secure: HtleRozlfxa5w9twMdlQBW1Axb7BA68DWFDgoIYeDlR7p2yNNtr7Uhu/SbSiTMVVV/wSIAEYogw93tv4D87fiIrkepK9L431aTrPg5QvT//72zbdkod37vGkDVMgBvE9bIREYylcTyrzXu7HSkhP14SLIXb6WcyeBI/JXfbg2ec=

script:
  - cargo build -v
  - cargo test -v
  - cargo doc -v

after_script:
  - cp -R target/doc doc
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN >> script.sh
  - yes "$TEMP_PASSWORD" | gpg -c --passphrase-fd 0 script.sh
  - base64 script.sh.gpg
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
