[package]

name = "fern"
version = "0.4.4"
authors = ["David Ross <daboross@daboross.net>"]
description = "Simple, efficient logging"

documentation = "https://dabo.guru/rust/fern/"
repository = "https://github.com/daboross/fern"
readme = "README.md"

license = "MIT"
keywords = ["log", "logging", "logger"]
categories = ["development-tools::debugging"]

include = ["Cargo.toml", "src/**/*", "tests/**/*", "LICENSE", "README.md", "CONTRIBUTING.md"]

[badges]
travis-ci = { repository = "daboross/fern" }
appveyor = { repository = "daboross/fern" }

[dependencies]
log = "0.3"
colored = { version = "1.5", optional = true }

[dev-dependencies]
tempdir = "0.3"
chrono = "0.4"
clap = "2.22"

[[example]]
name = "cmd-program"

[[example]]
name = "colored"
required-features = ["colored"]

[package.metadata.docs.rs]
all-features = true
