[package]

name = "fern"
version = "0.3.6-dev"
authors = ["Dabo Ross <daboross@daboross.net>"]
description = "Fern is a simple runtime-configurable logging library"

documentation = "https://dabo.guru/rust/fern/"
repository = "https://github.com/daboross/fern"

readme = "README.md"
keywords = ["log", "logging", "logger"]
license = "MIT"
categories = ["development-tools::debugging"]

[dependencies]
log = "0.3"

[dev-dependencies]
tempdir = "0.3"
chrono = "0.3"
