[package]

name = "fern"
# Remember to update html_root_url in src/lib.rs with each version.
version = "0.5.1"
authors = ["David Ross <daboross@daboross.net>"]
description = "Simple, efficient logging"

documentation = "https://docs.rs/fern/"
repository = "https://github.com/daboross/fern"
readme = "README.md"

license = "MIT"
keywords = ["log", "logging", "logger"]
categories = ["development-tools::debugging"]

include = ["Cargo.toml", "src/**/*", "tests/**/*", "examples/**/*", "LICENSE", "README.md", "CONTRIBUTING.md", "CHANGELOG.md"]

[badges]
travis-ci = { repository = "daboross/fern" }
appveyor = { repository = "daboross/fern" }

[dependencies]
log = { version = "0.4", features = ["std"] }
colored = { version = "1.5", optional = true }
syslog = { version = "3.3", optional = true }

[features]
syslog-3 = ["syslog"]

[dev-dependencies]
tempdir = "0.3"
chrono = "0.4"
clap = "2.22"

[[example]]
name = "cmd-program"

[[example]]
name = "colored"
required-features = ["colored"]

[[example]]
# different name so we know it's working correctly when looking at the syslog.
name = "fern-syslog"
path = "examples/syslog.rs"
required-features = ["syslog-3"]

[package.metadata.docs.rs]
all-features = true
